version: '3.8'
services:

    db:
        image: mysql
        container_name: db_rigole_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
    
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_rigole_docker
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev
    
    maildev:
        image: maildev/maildev
        container_name: maildev_rigole_docker
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 8081:80
        restart: always
        networks:
            - dev

    api:
        build:
            context: ./php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        container_name: api_rigole_docker
        ports:
            - 8088:80
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ../www-api:/var/www
        sysctls:
            - net.ipv4.ip_unprivileged_port_start=0
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:

